# Generated by Django 6.0 on 2026-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftivo', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
