# Generated by Django 6.0 on 2026-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftivo', '0004_contact_delete_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='enquiry',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='topic',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
