# Generated by Django 6.0 on 2026-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftivo', '0005_remove_contact_contact_remove_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='enquiry',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
