# Generated by Django 6.0 on 2026-01-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftivo', '0006_remove_contact_enquiry_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='topic',
            new_name='Topic',
        ),
    ]
