# Generated by Django 6.0 on 2026-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftivo', '0007_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Topic',
            new_name='topic',
        ),
    ]
