# Generated by Django 6.0 on 2026-02-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0002_remove_product_id_product_product_id_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('flavour_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(null=True)),
                ('flavour_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(null=True)),
                ('size_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
