# Generated by Django 6.0 on 2026-02-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0003_flavour_size_remove_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=100)),
                ('flavours', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
