# Generated by Django 6.0 on 2026-02-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
