# Generated by Django 6.0 on 2026-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0005_remove_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('Popular Dish', 'Popular Dish'), ('Main Course', 'Main Course')], max_length=20)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Flavour',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
