# Generated by Django 6.0 on 2026-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0006_fooditem_delete_flavour_delete_product_delete_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
