# Generated by Django 6.0 on 2026-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0007_delete_fooditem_order_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('Popular Dish', 'Popular Dish'), ('Main Course', 'Main Course')], max_length=20)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
