# Generated by Django 6.0 on 2026-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0008_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image', models.URLField(max_length=300)),
                ('size', models.CharField(max_length=50)),
                ('flavour', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('popular', 'Popular Dish'), ('main', 'Main Course'), ('beverage', 'Beverage')], default='popular', max_length=20)),
            ],
        ),
    ]
