# Generated by Django 6.0 on 2026-02-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0009_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
