# Generated by Django 6.0 on 2026-02-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0010_delete_fooditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
