# Generated by Django 6.0 on 2026-02-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0012_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='entry',
        ),
    ]
