# Generated by Django 6.0 on 2026-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0013_rename_product_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AddField(
            model_name='entry',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
