# Generated by Django 6.0 on 2026-02-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0023_remove_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
