# Generated by Django 6.0 on 2026-02-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0024_remove_order_user_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='door_number',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
