# Generated by Django 6.0 on 2026-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0025_remove_address_door_number_address_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
