# Generated by Django 6.0 on 2026-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0029_order_status_order_user_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
