# Generated by Django 6.0 on 2026-03-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0030_alter_order_order_id_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
