# Generated by Django 6.0 on 2026-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0031_remove_address_user_address_email_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
