# Generated by Django 6.0 on 2026-03-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0034_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
