# Generated by Django 6.0 on 2026-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0037_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
