# Generated by Django 6.0 on 2026-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0039_order_city_order_full_name_order_phone_order_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
