# Generated by Django 6.0 on 2026-03-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0040_alter_order_order_id_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
    ]
