# Generated by Django 6.0 on 2026-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0041_remove_order_city_remove_order_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
